### ISSUE TITLE
¿Hacemos público este foro de discusión?

### ISSUE THREAD

**Issue by mmanzano** [mmanzano/whisper-cat#3]
Ahora mismo esto es un repo privado. Mi idea era que si no llegaba a ningún lado o no era útil pues se elimina este repo y aquí no ha pasado nada :D. Pero podemos hacerlo público si creéis que podemos captar más gente de esa manera o al menos conseguir más información :+1:.

Os leo. :smiling_face_with_three_hearts:

**Comment by mmanzano** [comment]
Acabo de hacerlo público antes de que más gente opine. :)

**Comment by migueabellan** [comment]
Intentaremos no subir "claves privadas" xd
